' definition of the Item eventstorming/Element/Hotspot


skinparam file<<Comment>> {
    StereotypeFontSize $FONT_SIZE_SM
    shadowing false
    FontColor $FONT_COLOR
    BorderColor $FONT_COLOR
    BackgroundColor #FF3785
}

!procedure Comment($id, $label="")
  EsEntity('file', 'Hotspot', $id, $label)
!endprocedure
