' definition of the Item eventstorming/Element/Policy


skinparam file<<Policy>> {
    StereotypeFontSize $FONT_SIZE_SM
    shadowing false
    FontColor $FONT_COLOR
    BorderColor $FONT_COLOR
    BackgroundColor #DFD6FF
}

!procedure Policy($id, $label="")
  EsEntity('file', 'Policy', $id, $label)
!endprocedure
